# Introduction to TensorFlow

In [1]:
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow.keras.layers as tfl
from pprint import pprint

In [2]:
# The adapt() method
data = np.array(
    [
        [0.1, 0.2, 0.3],
        [0.8, 0.9, 1.0],
        [1.5, 1.6, 1.7],
    ]
)
layer = tfl.Normalization()
layer.adapt(data)
normalized_data = layer(data)

print("Features mean: %.2f" % (normalized_data.numpy().mean()))
print("Features std: %.2f" % (normalized_data.numpy().std()))


Features mean: -0.00
Features std: 1.00


In [7]:
print(normalized_data.numpy())

[[-1.2247449e+00 -1.2247449e+00 -1.2247448e+00]
 [ 0.0000000e+00 -1.0428640e-07  0.0000000e+00]
 [ 1.2247449e+00  1.2247448e+00  1.2247449e+00]]


In [9]:
data = [
    "ξεῖν᾽, ἦ τοι μὲν ὄνειροι ἀμήχανοι ἀκριτόμυθοι",
    "γίγνοντ᾽, οὐδέ τι πάντα τελείεται ἀνθρώποισι.",
    "δοιαὶ γάρ τε πύλαι ἀμενηνῶν εἰσὶν ὀνείρων:",
    "αἱ μὲν γὰρ κεράεσσι τετεύχαται, αἱ δ᾽ ἐλέφαντι:",
    "τῶν οἳ μέν κ᾽ ἔλθωσι διὰ πριστοῦ ἐλέφαντος,",
    "οἵ ῥ᾽ ἐλεφαίρονται, ἔπε᾽ ἀκράαντα φέροντες:",
    "οἱ δὲ διὰ ξεστῶν κεράων ἔλθωσι θύραζε,",
    "οἵ ῥ᾽ ἔτυμα κραίνουσι, βροτῶν ὅτε κέν τις ἴδηται.",
]
layer = tfl.TextVectorization()
layer.adapt(data)
vectorized_text = layer(data)
print(vectorized_text.numpy())

[[37 12 25  5  9 20 21  0  0]
 [51 34 27 33 29 18  0  0  0]
 [49 52 30 31 19 46 10  0  0]
 [ 7  5 50 43 28  7 47 17  0]
 [24 35 39 40  3  6 32 16  0]
 [ 4  2 15 14 22 23  0  0  0]
 [36 48  6 38 42  3 45  0  0]
 [ 4  2 13 41 53  8 44 26 11]]


In [18]:
vocab = ["a", "b", "c", "d"]
data = tf.constant(
    [
        ["a", "c", "d"],
        ["d", "z", "b"]
    ]
)
layer = tfl.StringLookup(vocabulary=vocab)
vectorized_data = layer(data)
print(vectorized_data.numpy())

[[1 3 4]
 [4 0 2]]
